version: "3.8"
services:
  mongo:
    image: "mongo"
    ports:
      - "27017:27017"
    volumes:
      - mongo-workout:/data/db
    env_file:
      - ./server/dev.env
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    volumes:
      - ./server/:/app
      - /app/node_modules
    depends_on:
      - mongo
    env_file:
      - ./server/dev.env
volumes:
  mongo-workout: