version: "3.8"
services:
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    volumes:
      - ./server/:/app
      - /app/node_modules
    env_file:
      - ./server/dev.env